Repository nextcloud/collectives, pull requests merged in 2023-08, with the labels that each got.

#812 List recent pages and members on landing page
  cypress/e2e/page-landingpage.spec.js
  src/components/LastUserBubble.vue
  src/components/Member/CurrentMembers.vue
  src/components/Member/Member.vue
  src/components/Member/MemberPicker.vue
  src/components/Nav/CollectiveMembersModal.vue
  src/components/Page.vue
  src/components/Page/LandingPageWidgets.vue
  src/components/Page/LandingPageWidgets/MembersWidget.vue
  src/components/Page/LandingPageWidgets/RecentPageTile.vue
  src/components/Page/LandingPageWidgets/RecentPagesWidget.vue
  src/components/Page/LandingPageWidgets/WidgetHeading.vue
  src/components/Page/PageInfoBar.vue
  src/components/Page/TextEditor.vue
  src/components/SkeletonLoading.vue
  src/store/circles.js
  src/store/pages.js
Labels: enhancement, 3. to review

#817 [main] Update nextcloud/ocp dependency
  composer.lock
  tests/stub.phpstub
Labels: 3. to review, dependencies

#819 fix(webpack): set `__webpack_public_path__`
  cypress/support/commands.js
  src/main.js
Labels: 3. to review

#822 fix: Make sure collectives own scroll area is used for menubar stickyness
  src/Collectives.vue
  src/components/Page.vue
  src/components/Page/Editor.vue
Labels: bug, 3. to review

#823 Prepare for 2.7.0 release
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#834 fix: Use shared init file to properly set nonce for async component loading
  src/main.js
  src/shared-init.js
Labels: bug, 3. to review
