Repository nextcloud/collectives, pull requests merged in 2023-05, with the labels that each got.

#661 Fix "page not found" for deleted public share links
  cypress/e2e/collective-share.spec.js
Labels: tests, 3. to review

#658 fix: Use getDisplayName to avoid calling on null
  lib/Service/PageService.php
Labels: bug, 3. to review

#617 Flag circles for collectives as managed by app
  .github/workflows/behat-sqlite-encryption.yml
  .github/workflows/behat-sqlite.yml
  lib/Service/CircleHelper.php
  lib/Service/CollectiveService.php
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/collective.feature
  tests/psalm-baseline.xml
  tests/stub.phpstub
Labels: bug, 3. to review

#673 Update NPM dependencies
  package-lock.json
Labels: 4. to release, dependencies

#674 Fix EmptyContent title and description in PageNotFound
  src/components/Nav/NewCollectiveModal.vue
  src/components/Page/PageNotFound.vue
Labels: bug, 4. to release

#680 Use the color-primary-element* variables
  src/components/Member/MemberSearchResult.vue
  src/components/Page/PagePicker.vue
  src/components/PageList.vue
  src/components/PageList/Item.vue
Labels: bug, design, 3. to review

#686 Fix relative paths to pages from landing page
  cypress/e2e/pages-links.spec.js
  src/components/Page/RichText.vue
Labels: bug: regression, 3. to review

#708 chore: update workflows from templates
  .github/workflows/behat-sqlite-encryption.yml
  .github/workflows/behat-sqlite.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
  composer.json
Labels: 3. to review, dependencies, automated

#703 Add `npm run serve` and update development docs
  DEVELOPING.md
  package.json
  src/files.js
  src/reference.js
  src/shared-init.js
  webpack.js
Labels: documentation, 3. to review
