Repository nextcloud/collectives, pull requests merged in 2023-06, with the labels that each got.

#714 [main] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#711 chore: update workflows from templates
  .github/workflows/app-upgrade-mysql.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/occ-cli-mysql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: 3. to review, dependencies, automated

#700 Add page trash backend
  .github/workflows/occ-cli-mysql.yml
  appinfo/info.xml
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/BackgroundJob/ExpirePageTrash.php
  lib/Command/PageTrashCleanup.php
  lib/Controller/PageController.php
  lib/Controller/PageTrashController.php
  lib/Controller/PublicPageController.php
  lib/Controller/PublicPageTrashController.php
  lib/Db/CollectiveMapper.php
  lib/Db/Page.php
  lib/Db/PageMapper.php
  lib/Fs/NodeHelper.php
  lib/Migration/Version000200Date20200822000000.php
  lib/Migration/Version020600Date20230412160400.php
  lib/Migration/Version020600Date20230519000000.php
  lib/Model/PageInfo.php
  lib/Service/CollectiveService.php
  lib/Service/PageService.php
  lib/Trash/CollectivePageTrashItem.php
  lib/Trash/PageTrashBackend.php
  lib/Trash/PageTrashManager.php
  lib/Versions/VersionsBackend.php
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/mountpoint.feature
  tests/Integration/features/pages.feature
  tests/Integration/features/pagesDisabledTrashAndVersion.feature
  tests/Integration/features/publicShare.feature
  tests/Unit/Fs/NodeHelperTest.php
  tests/Unit/Service/CollectiveServiceTest.php
  tests/Unit/Service/PageServiceTest.php
  tests/stub.phpstub
Labels: enhancement, 3. to review

#718 Install sqlite extensions in all workflows, as we always need it
  .github/workflows/app-upgrade-mysql.yml
  .github/workflows/occ-cli-mysql.yml
Labels: tests, 3. to review

#721 Fix path to collective in navigation of public share
  src/components/Nav/CollectiveListItem.vue
  src/store/collectives.js
Labels: bug, 3. to review

#730 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#728 Fix localization section for select emoji
  src/components/Page/PageActionMenu.vue
Labels: bug, l10n, 3. to review

#733 Add extra default route without path parameter
  appinfo/routes.php
  lib/Controller/StartController.php
Labels: bug

#740 Update Github workflow files from templates
  .github/workflows/app-upgrade-mysql.yml
  .github/workflows/behat-sqlite-encryption.yml
  .github/workflows/behat-sqlite.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/occ-cli-mysql.yml
  .github/workflows/pages.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: tests, 3. to review

#736 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#743 fix: Switch to ObjectStoreScanner if NoopScanner is not available
  lib/Mount/CollectiveStorage.php
Labels: bug, 3. to review

#745 fix(cypress): Fix flaky tests from `pages.spec.js` on stable25
  cypress/e2e/pages.spec.js
Labels: 4. to release
