Repository nextcloud/collectives, pull requests merged in 2023-11, with the labels that each got.

#985 chore(ci): Update Github workflows from templates
  .github/workflows/app-upgrade-mysql.yml
  .github/workflows/app-upgrade-postgres.yml
  .github/workflows/behat-sqlite-encryption.yml
  .github/workflows/behat-sqlite.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-eslint-when-unrelated.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/occ-cli-mysql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review, technical debt

#987 fix(composer): Add dependency on `php-pdo_sqlite`
  composer.json
Labels: bug, tests, 3. to review

#991 chore(info.xml): Add `ext-pdo` and `ext-pdo_sqlite` as lib dependencies
  appinfo/info.xml
Labels: 3. to review, technical debt

#992 Revert "chore(info.xml): Add `ext-pdo` and `ext-pdo_sqlite` as lib dependencies"
  appinfo/info.xml
Labels: bug: regression, 3. to review

#990 chore: Update issue template
  .github/ISSUE_TEMPLATE/Bug_report.md
Labels: enhancement, 3. to review

#994 fix(ci): Install PHP extensions in psalm and lint-php-cs workflows
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/psalm.yml
Labels: tests, 3. to review

#995 fix(LazyFolder): FileInfo interface added `getMedata` function
  lib/Mount/LazyFolder.php
Labels: bug, backend, 3. to review

#898 enh(dashboard): add recent pages dashboard widget
  cypress/e2e/dashboard-widget.spec.js
  cypress/support/commands.js
  lib/AppInfo/Application.php
  lib/Dashboard/RecentPagesWidget.php
  lib/Model/RecentPage.php
  lib/Service/CollectiveHelper.php
  lib/Service/RecentPagesService.php
  tests/psalm-baseline.xml
Labels: 3. to review

#996 fix(deps): Update NPM dependencies
  .github/workflows/behat-sqlite-encryption.yml
  package-lock.json
Labels: 3. to review, dependencies

#1000 Prepare 2.9.0 release with Nextcloud 28 support
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#1002 test(ci): Make summary job depend on changes in cypress workflow
  .github/workflows/cypress.yml
Labels: tests, 3. to review

#1004 fix(Collective): Fix alignment of page heading skeleton
  src/components/Collective.vue
  src/css/editor.scss
Labels: design, 3. to review

#1008 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1012 fix(backlinks): Accept `<link>` syntax as valid in parsed markdown
  lib/Service/PageService.php
  tests/Unit/Service/PageServiceTest.php
Labels: bug, backend, 3. to review

#1013 fix(dashboard): Display parent page path in recent pages widget
  lib/Dashboard/RecentPagesWidget.php
  lib/Model/RecentPage.php
  lib/Service/RecentPagesService.php
Labels: 3. to review

#1014 fix(page): Save document on <Ctrl>-<S> when page title is focussed
  src/components/Page.vue
  src/components/Page/TextEditor.vue
  src/mixins/editorMixin.js
Labels: 3. to review

#1015 fix(FileListInfo): Don't show info header if collectivesFolder is `/`
  src/views/FileListInfo.vue
Labels: bug, 3. to review

#1018 feat(release): Prepare 2.9.1 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#1020 fix(dasbhoard): Respect item limit
  lib/Dashboard/RecentPagesWidget.php
Labels: bug, 3. to review

#1023 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
