Repository nextcloud/collectives, pull requests merged in 2023-02, with the labels that each got.

#540 fix: Adapt return type for Nextcloud 26
  lib/ACL/ACLStorageWrapper.php
  lib/ACL/ACLStorageWrapper25.php
  lib/ACL/ACLStorageWrapper26.php
  lib/Mount/CollectiveFolderManager.php
  psalm.xml
  tests/Unit/ACL/ACLStorageWrapperTest.php
Labels: bug, 3. to review

#553 Update engines workflow for prevent deprecation warnings
  .github/dependabot.yml
  .github/workflows/cypress.yml
Labels: 3. to review, dependencies

#539 Reuse the circle we already have to get the level for the user
  lib/Service/CollectiveHelper.php
Labels: 3. to review

#545 fix: Prevent empty additional pages added when printing
  src/views/CollectivePrintView.vue
Labels: enhancement, 3. to review

#562 Use MDI icon for collective settings action
  src/components/Collective/CollectiveActions.vue
Labels: 3. to review

#564 Fix sticky text menubar
  src/components/Page/PageInfoBar.vue
  src/components/Page/TextEditor.vue
Labels: 3. to review

#565 Readonly view fixes in page titlebar
  cypress/e2e/collective-readonly.spec.js
  src/components/Page.vue
  src/components/Page/PageActionMenu.vue
Labels: 3. to review

#551 Fix `new collective` name input elements
  src/components/Nav/NewCollective.vue
Labels: design, enhancement, 3. to review

#527 Add reference provider and basic reference widget
  .github/workflows/cypress.yml
  cypress/Dockerfile
  cypress/docker-compose.yml
  cypress/e2e/pages.spec.js
  cypress/entrypoint.sh
  cypress/runLocal.sh
  lib/AppInfo/Application.php
  lib/Listeners/CollectivesReferenceListener.php
  lib/Reference/PageReferenceProvider.php
  lib/Reference/SearchablePageReferenceProvider.php
  lib/Search/CollectiveProvider.php
  lib/Search/PageProvider.php
  lib/Service/CollectiveService.php
  lib/Service/PageService.php
  package-lock.json
  package.json
  src/reference.js
  src/views/PageReferenceWidget.vue
  tests/Unit/Service/CollectiveServiceTest.php
  tests/psalm-baseline.xml
  webpack.js
Labels: enhancement, feature: link handling, 3. to review

#504 Replace the 'new collective' form with a modal
  cypress/e2e/apps.spec.js
  cypress/e2e/collective.spec.js
  cypress/support/commands.js
  package-lock.json
  package.json
  src/components/Member/MemberPicker.vue
  src/components/Member/MemberSearchResult.vue
  src/components/Nav/NewCollective.vue
  src/components/Nav/NewCollectiveModal.vue
  src/components/Navigation.vue
  src/constants.js
  src/store/actions.js
  src/store/circles.js
  src/views/Home.vue
Labels: enhancement, 2. developing
