Repository nextcloud/collectives, pull requests merged in 2023-09, with the labels that each got.

#856 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#857 ci(cypress): Test against stable27
  .github/workflows/cypress.yml
Labels: tests, 3. to review

#864 fix(CollectiveFolderManager): Use our own LazyFolder implementation
  lib/Mount/CollectiveFolderManager.php
  lib/Mount/LazyFolder.php
  lib/Trash/PageTrashBackend.php
  tests/Integration/features/pagesDisabledTrashAndVersion.feature
Labels: bug: regression, 3. to review

#869 test(cypress): More flexible selectors for Nextcloud 25-28
  cypress/e2e/apps.spec.js
  cypress/e2e/collective.spec.js
  cypress/e2e/page-details.spec.js
  cypress/e2e/pages.spec.js
  cypress/e2e/settings.spec.js
Labels: tests, 3. to review

#833 fix: Fallback to old eventdispatcher on older releases
  .github/workflows/phpunit-sqlite.yml
  lib/Versions/CollectiveVersionsExpireManager.php
  tests/Unit/BackgroundJob/CollectiveVersionsExpireManagerTest.php
Labels: bug, 3. to review

#862 fix(RecentPagesWidget): Remove margin of slider button
  src/components/Page/LandingPageWidgets/RecentPagesWidget.vue
Labels: bug, 3. to review

#870 ci(cypress): disable parallelization via Cypress cloud
  .github/workflows/cypress.yml
Labels: tests, 3. to review

#871 feat(release): prepare for 2.7.1 release
  CHANGELOG.md
  appinfo/info.xml
  docs/content/administration/_index.md
Labels: documentation, 3. to review

#874 feat(page): Add toggle for full width page view
  cypress/e2e/pages.spec.js
  package-lock.json
  package.json
  src/components/Collective.vue
  src/components/Page.vue
  src/components/Page/Editor.vue
  src/components/Page/LandingPageWidgets.vue
  src/components/Page/LandingPageWidgets/RecentPagesWidget.vue
  src/components/Page/PageActionMenu.vue
  src/components/Page/PageInfoBar.vue
  src/components/Page/RichText.vue
  src/components/Page/TextEditor.vue
  src/components/Page/Version.vue
  src/components/PagePrint.vue
  src/components/SkeletonLoading.vue
  src/css/editor.scss
  src/store/actions.js
  src/store/mutations.js
  src/store/pages.js
Labels: enhancement, 3. to review

#896 Fix visual glitches
  src/Collectives.vue
  src/components/Collective.vue
  src/components/Page/LandingPageWidgets/RecentPageTile.vue
Labels: bug, design, papercut, 3. to review

#894 Collapsible recent pages
  appinfo/info.xml
  appinfo/routes.php
  cypress/e2e/page-landingpage.spec.js
  lib/Controller/CollectiveUserSettingsController.php
  lib/Db/Collective.php
  lib/Db/CollectiveUserSettings.php
  lib/Db/CollectiveUserSettingsMapper.php
  lib/Migration/Version020800Date20230911000000.php
  lib/Model/CollectiveInfo.php
  lib/Service/CollectiveHelper.php
  lib/Service/CollectiveService.php
  lib/Service/CollectiveUserSettingsService.php
  src/components/Page/LandingPageWidgets.vue
  src/components/Page/LandingPageWidgets/MembersWidget.vue
  src/components/Page/LandingPageWidgets/RecentPagesWidget.vue
  src/components/Page/LandingPageWidgets/WidgetHeading.vue
  src/store/actions.js
  src/store/collectives.js
  tests/Unit/Db/CollectiveUserSettingsTest.php
  tests/Unit/Service/CollectiveServiceTest.php
  tests/Unit/Service/CollectiveUserSettingsServiceTest.php
Labels: bug, 3. to review

#903 fix(PageTrashBackend): Ignore emty relativePath in `getTrashNodeById()`
  lib/Trash/PageTrashBackend.php
Labels: bug, backend, 3. to review

#907 fix(EmojiPicker): allow to unselect collective and page emoji
  cypress/e2e/collective-settings.spec.js
  cypress/e2e/pages.spec.js
  lib/Db/Collective.php
  lib/Db/Page.php
  lib/Service/CollectiveService.php
  lib/Service/PageService.php
  src/components/Icon/CollectivesIcon.vue
  src/components/Icon/PageIcon.vue
  src/components/Icon/PageTemplateIcon.vue
  src/components/Icon/PagesTemplateIcon.vue
  src/components/Nav/CollectiveSettings.vue
  src/components/Page.vue
Labels: bug, ui/ux, 2. developing

#906 fix(cypress): Always open new folder in file picker
  cypress/e2e/settings.spec.js
  cypress/runLocal.sh
Labels: tests, 3. to review
