Repository nextcloud/collectives, pull requests merged in 2023-07, with the labels that each got.

#752 Lower minimum page list width to 15%
  src/views/CollectiveView.vue
Labels: 3. to review

#753 fix(backend): don't update subpage order if page gets renamed (not moved)
  lib/Service/PageService.php
Labels: bug, bug: regression, 3. to review

#754 fix(backend): typo in page trash expire function
  lib/Trash/PageTrashBackend.php
Labels: bug, 3. to review

#763 fix(backend): remove duplicate `/` from links to app in search providers
  lib/Search/CollectiveProvider.php
  lib/Search/PageContentProvider.php
  lib/Search/PageProvider.php
Labels: 3. to review

#772 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#775 fix(search): generate absolute links, fixes previews from smart picker
  lib/Search/CollectiveProvider.php
  lib/Search/PageContentProvider.php
  lib/Search/PageProvider.php
Labels: bug: regression, 3. to review

#776 fix(release): Prepare for 2.6.1 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#792 test(cypress): Fix selector for viewer title in Nextcloud 28
  cypress/e2e/pages-links.spec.js
Labels: tests, 3. to review

#790 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#783 Set `label` attribute for NcTextField
  src/components/PageList.vue
Labels: 3. to review

#649 feat: add component SkeletonLoading
  src/components/Collective.vue
  src/components/Navigation.vue
  src/components/Page.vue
  src/components/Page/RichText.vue
  src/components/Page/TextEditor.vue
  src/components/PageList.vue
  src/components/SkeletonLoading.vue
  src/mixins/pageMixin.js
  src/store/circles.js
  src/store/pages.js
Labels: enhancement, 3. to review

#795 fix(editor): Use the `autofocus` command from Text if available
  src/components/Page/TextEditor.vue
Labels: upstream: text, 2. developing

#802 style(css): Remove superfluous `y` values in SkeletenLoading
  src/components/SkeletonLoading.vue
Labels: 3. to review

#804 Manage members in app
  .github/workflows/cypress.yml
  cypress/e2e/apps.spec.js
  cypress/e2e/collective-members.spec.js
  cypress/support/commands.js
  src/Collectives.vue
  src/components/Collective/CollectiveActions.vue
  src/components/Member/CurrentMembers.vue
  src/components/Member/Hint.vue
  src/components/Member/Member.vue
  src/components/Member/MemberPicker.vue
  src/components/Member/MemberSearchResult.vue
  src/components/Member/MemberSearchResults.vue
  src/components/Member/SelectedMembers.vue
  src/components/Nav/CollectiveMembersModal.vue
  src/components/Nav/CollectiveSettings.vue
  src/components/Nav/NewCollectiveModal.vue
  src/components/Navigation.vue
  src/components/SkeletonLoading.vue
  src/constants.js
  src/store/actions.js
  src/store/circles.js
  src/store/collectives.js
  src/store/mutations.js
Labels: 2. developing

#811 fix(backend): Use IDispatcher instead of Symfony EventDispatcher
  lib/Versions/CollectiveVersionsExpireManager.php
Labels: 3. to review, technical debt
