Repository nextcloud/collectives, pull requests merged in 2023-10, with the labels that each got.

#912 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#909 test(ci): Bump PHP version to 8.2 in most cases
  .github/workflows/app-upgrade-mysql.yml
  .github/workflows/behat-sqlite-encryption.yml
  .github/workflows/behat-sqlite.yml
  .github/workflows/cypress.yml
  .github/workflows/occ-cli-mysql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: tests

#913 feat(release): Prepare for 2.8.0 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#914 fix(migrations): set default value for new not null column
  lib/Migration/Version020800Date20230911000000.php
Labels: bug, 3. to review

#915 Prepare 2.8.1 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#924 fix(db): make settings field from collectives_user_settings type string
  appinfo/info.xml
  lib/Db/CollectiveUserSettings.php
  lib/Migration/Version000003Date20200720000000.php
  lib/Migration/Version000200Date20200822000000.php
  lib/Migration/Version000400Date20210324000000.php
  lib/Migration/Version000500Date20210421000000.php
  lib/Migration/Version001600Date20211025000000.php
  lib/Migration/Version002000Date20220103000000.php
  lib/Migration/Version002000Date20220210000000.php
  lib/Migration/Version010200Date20220616000000.php
  lib/Migration/Version010300Date20220623000000.php
  lib/Migration/Version020100Date20221111000000.php
  lib/Migration/Version020600Date20230412160400.php
  lib/Migration/Version020600Date20230519000000.php
  lib/Migration/Version020802Date20231004000000.php
  psalm.xml
Labels: 2. developing

#925 Prepare for 2.8.2 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#928 fix(PageService): preg_quote `trusted_domains` before using in regexp
  lib/Service/PageService.php
Labels: bug, 3. to review

#941 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#946 Public share fixes
  lib/Controller/PublicStartController.php
  src/components/Collective/CollectiveActions.vue
Labels: bug, ui/ux, 3. to review

#948 refactor(routes): Remove `parentId` parameter from page routes
  appinfo/routes.php
  cypress/e2e/collective-share.spec.js
  cypress/e2e/pages.spec.js
  lib/Controller/PageController.php
  lib/Controller/PublicPageController.php
  lib/Service/PageService.php
  src/components/Page.vue
  src/components/Page/PageActionMenu.vue
  src/mixins/pageMixin.js
  src/store/pages.js
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/pages.feature
  tests/Integration/features/pagesDisabledTrashAndVersion.feature
  tests/Integration/features/publicShare.feature
  tests/Unit/Service/PageServiceTest.php
Labels: 3. to review, technical debt

#965 fix(PageActionMenu): Fix link to file in files app on Nextcloud 28
  src/components/Page/PageActionMenu.vue
Labels: bug: regression, 3. to review

#961 chore(php): Add PHP 8.3 to test matrix
  .github/workflows/behat-sqlite.yml
  .github/workflows/lint-php.yml
Labels: tests, 3. to review

#963 Copy/move pages in/between collectives
  appinfo/routes.php
  cypress/e2e/page-list.spec.js
  lib/Controller/PageController.php
  lib/Controller/PublicPageController.php
  lib/Service/PageService.php
  lib/Service/SubpageOrderService.php
  src/components/Collective.vue
  src/components/Page/LandingPageWidgets/RecentPageTile.vue
  src/components/Page/MoveModal.vue
  src/components/Page/MoveOrCopyModal.vue
  src/components/Page/PageActionMenu.vue
  src/components/Page/PagePicker.vue
  src/components/PageList.vue
  src/mixins/pageMixin.js
  src/store/actions.js
  src/store/collectives.js
  src/store/mutations.js
  src/store/pageExtracts.js
  src/store/pages.js
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/pages.feature
  tests/Integration/features/publicShare.feature
  tests/Unit/Service/PageServiceTest.php
  tests/Unit/Service/SubpageOrderServiceTest.php
Labels: enhancement, 3. to review

#967 fix(editor): Set CSS variable `--text-editor-max-width` per default
  src/components/Page.vue
  src/components/Page/Editor.vue
  src/components/Page/LandingPageWidgets.vue
  src/components/Page/PageInfoBar.vue
  src/components/Page/TextEditor.vue
  src/components/Page/Version.vue
  src/components/SkeletonLoading.vue
  src/css/editor.scss
Labels: bug: regression, 3. to review

#971 Printing fixes
  src/Collectives.vue
  src/components/Collective/CollectiveActions.vue
  src/components/CollectivePrint.vue
  src/components/Page/LandingPageWidgets.vue
  src/components/Page/RichText.vue
  src/components/Page/TextEditor.vue
  src/components/PageList/Item.vue
  src/components/PagePrint.vue
Labels: bug, 3. to review
