Repository nextcloud/collectives, pull requests merged in 2024-10, with the labels that each got.

#1544 chore(build): Exclude rector.php when building the release tarball
  Makefile
Labels: bug, 3. to review

#1546 fix(PageList): Make header, landing page and trash sticky again
  src/components/PageList.vue
  src/components/PageList/PageTrash.vue
Labels: bug, bug: regression, 3. to review

#1548 fix(share): Add owner sharing permission for folder of public share
  lib/Db/Collective.php
Labels: bug, bug: regression, 3. to review

#1555 fix: Alignment of landing page widgets
  src/components/Page/LandingPageWidgets.vue
  src/components/Page/TextEditor.vue
  src/css/editor.scss
Labels: bug: regression, 3. to review

#1556 perf(dashboard): Use storage id for more performant index usage on dashboard query
  lib/Service/RecentPagesService.php
  tests/Unit/Service/RecentPagesServiceTest.php
Labels: bug, 3. to review, performance

#1557 fix(favorites): Show details when clicking on a favorite
  src/components/PageList/PageFavorites.vue
Labels: 3. to review

#1550 fix(PageInfoBar): Update timestamp when page gets saved via "Done" button
  src/components/Page/TextEditor.vue
  src/constants.js
  src/mixins/editorMixin.js
  src/stores/root.js
Labels: bug, 3. to review
