Repository nextcloud/collectives, pull requests merged in 2024-09, with the labels that each got.

#1457 chore(CI): Updating renovate-approve-merge.yml workflow from template
  .github/workflows/renovate-approve-merge.yml
Labels: dependencies

#1458 fix(CollectiveSettings): Rename collective
  src/components/Nav/CollectiveSettings.vue
  src/stores/collectives.js
Labels: bug: regression, 3. to review

#1459 fix(PageList): Sort numbers numeric (2 > 10)
  src/tests/util/sortOrders.spec.js
  src/util/sortOrders.js
Labels: bug, 3. to review

#1460 fix(backlinks): Detect links with title in markdown syntax
  lib/Service/PageService.php
  tests/Unit/Service/PageServiceTest.php
Labels: 3. to review

#1465 fix(Navigation): Show details when switching collective on mobile
  src/components/Nav/CollectiveListItem.vue
Labels: bug, 3. to review, mobile

#1464 fix(error): Improve design of missing app error box
  templates/error.php
Labels: bug, 3. to review

#1470 fix: search dialog stick to bottom of page
  src/components/SearchDialog.vue
Labels: bug, 3. to review

#1467 fix(PageList): Calculate scroller height dynamically for filtered view
  package-lock.json
  package.json
  src/components/PageList.vue
Labels: bug, 3. to review

#1476 fix(mount): public shares always get permissions of a simple user
  lib/AppInfo/Application.php
  lib/Db/Collective.php
  lib/Mount/MountProvider.php
  tests/Integration/config/behat.yml
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/mountpoint.feature
Labels: bug, 3. to review

#1474 fix(css): Use flexbox to align editor container and search dialog
  src/components/Collective.vue
  src/components/Page/PageInfoBar.vue
  src/components/Page/TextEditor.vue
  src/components/SearchDialog.vue
  src/css/editor.scss
Labels: bug, 3. to review

#1491 fix(CollectiveStorage): adjust `getOwner` to NC31
  lib/Mount/CollectiveStorage.php
Labels: bug: regression, 3. to review

#1493 Use the dark svg for widget icon
  lib/Dashboard/RecentPagesWidget.php
Labels: bug, 3. to review

#1481 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1499 fix(Makefile): Run distclean as dependency of release
  Makefile
Labels: bug, 3. to review

#1498 fix(editor): Add bottom border to menubar
  src/components/Collective.vue
  src/components/Page/PageInfoBar.vue
  src/css/editor.scss
Labels: bug, design, 3. to review

#1502 fix(PageList): Add icon to clear the filter/search string
  src/components/PageList.vue
Labels: bug, papercut, ui/ux, 3. to review

#1505 fix(member): close actions menu when scrolling members
  src/components/Member/Member.vue
  src/components/Member/MemberPicker.vue
Labels: bug, papercut, ui/ux, 3. to review

#1506 fix(PageService): Handle errors with missing index files
  lib/Service/PageService.php
Labels: bug, backend, 3. to review

#1509 fix: Allow to mount the collectives user folder into a subfolder
  lib/Controller/SettingsController.php
  lib/Mount/MountProvider.php
  src/components/Nav/CollectivesGlobalSettings.vue
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/mountpoint.feature
  tests/Unit/Controller/SettingsControllerTest.php
Labels: bug, 3. to review

#1503 chore(release): Prepare 2.14.4 release
  CHANGELOG.md
  appinfo/info.xml
Labels: enhancement, 3. to review
