Repository nextcloud/collectives, pull requests merged in 2024-08, with the labels that each got.

#1416 fix(share): Fix updating shares with empty password, feedback on error
  lib/Controller/ShareController.php
  lib/Service/CollectiveShareService.php
  src/components/PageSidebar/SharingEntryLink.vue
Labels: 3. to review

#1403 perf: Optimize getPagesFromFolder to avoid requests for files that already get obtained through directory listing
  lib/Service/PageService.php
  tests/Unit/Service/PageServiceTest.php
Labels: 3. to review, performance

#1418 fix(shares): Provide hidden element `isPublic` on public shares.
  src/Collectives.vue
  src/components/CollectivePrint.vue
Labels: bug, 3. to review

#1386 Save full width of page on server
  appinfo/routes.php
  cypress/e2e/pages.spec.js
  lib/Controller/PageController.php
  lib/Db/Page.php
  lib/Migration/Version021200Date20240725154232.php
  lib/Model/PageInfo.php
  lib/Service/PageService.php
  package-lock.json
  package.json
  src/apis/collectives/pages.js
  src/components/Page.vue
  src/components/Page/PageActionMenu.vue
  src/components/Page/Version.vue
  src/stores/pages.js
  tests/Integration/features/bootstrap/FeatureContext.php
  tests/Integration/features/pages.feature
Labels: feedback-requested

#1427 chore(release): Prepare for 2.14.0 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#1429 fix(Navigation): use `NcAppNavigationNew` for new button
  src/components/Navigation.vue
Labels: bug, 3. to review

#1430 fix(titlebar): bring back top padding on Nextcloud < 30
  src/components/Page.vue
  src/components/Page/Version.vue
Labels: 3. to review

#1432 fix(PageService): Don't run `getFullWidth()` on null page
  lib/Service/PageService.php
Labels: bug: regression, 3. to review

#1433 chore(release): Prepare 2.14.1 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#1438 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/renovate-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review, dependencies, automated

#1439 fix(PageService): Always pass a bool to `fromFile()` for `fullWidth`
  lib/Service/PageService.php
Labels: bug: regression, 3. to review

#1440 fix(PageList): Fix moving page by drag and drop
  src/components/PageList/Draggable.vue
  src/components/PageList/Item.vue
  src/mixins/pageMixin.js
Labels: bug: regression, 3. to review

#1441 chore(release): Prepare 2.14.2 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#1442 fix(deps): npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#1449 fix(FileIndexer): Don't choke on missing files
  lib/Search/FileSearch/FileIndexer.php
Labels: bug, 3. to review

#1450 fixes to display latest page content in reader
  src/mixins/editorMixin.js
  src/mixins/pageContentMixin.js
Labels: bug, 3. to review
