Repository nextcloud/collectives, pull requests merged in 2024-07, with the labels that each got.

#1348 test(cypress): Wait until empty folder is loaded in settings test
  cypress/e2e/settings.spec.js
Labels: tests, 3. to review

#1346 chore: Drop Nextcloud 26 support (no longer supported)
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/workflows/behat-sqlite-encryption.yml
  .github/workflows/behat-sqlite.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
  appinfo/info.xml
  cypress/e2e/collective-share.spec.js
  cypress/e2e/page-details.spec.js
  cypress/e2e/pages-links.spec.js
  cypress/e2e/pages.spec.js
  cypress/support/commands.js
Labels: 3. to review

#1355 chore(deps): Update composer dependencies to stable27 baseline
  composer.json
  composer.lock
Labels: 3. to review

#1363 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1362 chore: update workflows from templates
  .github/workflows/app-upgrade-mysql.yml
  .github/workflows/app-upgrade-postgres.yml
  .github/workflows/behat-sqlite-encryption.yml
  .github/workflows/behat-sqlite.yml
  .github/workflows/cypress-e2e.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/occ-cli-mysql.yml
  .github/workflows/pages.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/renovate-approve-merge.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review, dependencies, automated

#1378 fix(sharing): Use password policy API for generating password if enabled
  .github/workflows/cypress-e2e.yml
  cypress/e2e/page-share.spec.js
  package-lock.json
  package.json
  src/components/PageSidebar/SharingEntryLink.vue
  src/mixins/serverCapabilities.js
Labels: bug, 3. to review

#1387 chore(release): Prepare 2.13.0 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review

#1391 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1393 ci(cypress): Use cypress-split for running tests in parallel
  .github/workflows/cypress-e2e.yml
  cypress.config.js
  package-lock.json
  package.json
Labels: 3. to review
