Repository nextcloud/collectives, pull requests merged in 2024-01, with the labels that each got.

#1078 fix: Do not load editor on unrelated pages
  lib/Listeners/BeforeTemplateRenderedListener.php
  tests/stub.phpstub
Labels: bug, 3. to review

#1089 chore: Add PHP-CS-Fixer cache to .gitignore
  .gitignore
Labels: 3. to review, technical debt

#1088 feat(dashboard): Add icon URL
  lib/Dashboard/RecentPagesWidget.php
Labels: enhancement, 3. to review

#1079 Update npm and node engines versions
  package.json
Labels: dependencies
