Repository nextcloud/collectives, pull requests merged in 2024-05, with the labels that each got.

#1253 Make permanently delete collective buttons readable
  src/components/Nav/CollectivesTrash.vue
Labels: bug, design, ui/ux

#1229 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#1230 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#1252 Add setup checks for sqlite driver & circles app
  lib/AppInfo/Application.php
  lib/SetupChecks/CirclesAppIsEnableCheck.php
  lib/SetupChecks/PDOSQLiteDriverIsEnableCheck.php
  psalm.xml
Labels: enhancement, 2. developing

#1261 chore(CollectivesTrash): Replace `»«` quotes with `""`
  src/components/Nav/CollectivesTrash.vue
Labels: papercut, 3. to review

#1267 docs: Add documentation about using `group_everyone` app
  docs/content/administration/_index.md
Labels: documentation, 2. developing

#1290 fix(CollectiveMapper): Always return trashed collectives as simple list
  lib/Db/CollectiveMapper.php
Labels: bug, 3. to review
