Repository nextcloud/collectives, pull requests merged in 2024-06, with the labels that each got.

#1305 fix(draggable): `draggable` attribute to HTML elements requires `true`
  src/components/PageList/Item.vue
Labels: bug, 3. to review

#1315 fix(debounce): Register debounced functions in instance context
  src/components/Member/MemberPicker.vue
  src/components/Page/LandingPageWidgets/MembersWidget.vue
  src/components/Page/LandingPageWidgets/RecentPagesWidget.vue
  src/mixins/editorMixin.js
Labels: bug: regression, 3. to review

#1240 add content search to collectives
  appinfo/routes.php
  lib/Controller/PageController.php
  src/apis/collectives/pages.js
  src/apis/collectives/urls.js
  src/components/PageList.vue
Labels: enhancement, 2. developing

#1316 fix(MembersWidget): Resize according to available space
  src/components/Page/LandingPageWidgets/MembersWidget.vue
Labels: bug, 3. to review

#1337 fix: Properly check for fileId parameter
  lib/Reference/SearchablePageReferenceProvider.php
Labels: bug, 3. to review

#1332 fix: Avoid reusing the collectives user folder for different users
  lib/Fs/UserFolderHelper.php
Labels: bug, 3. to review, performance

#1341 fix(PageList): Reset content filtered pages when switching collectives
  src/components/PageList.vue
Labels: bug, 3. to review

#1320 fix(recentPages): Allow toggleing in public share
  src/components/Page/LandingPageWidgets/RecentPagesWidget.vue
Labels: bug, 3. to review
