Repository nextcloud/collectives, pull requests merged in 2024-12, with the labels that each got.

#1592 fix(circles): Use `probeCircles()` instead of `getCircles()`
  lib/Service/CircleHelper.php
  lib/Service/CollectiveHelper.php
  tests/stub.phpstub
Labels: 3. to review, technical debt, performance 🚀

#1616 chore(release): Prepare 2.15.2 release
  .github/workflows/cypress-e2e.yml
  CHANGELOG.md
  appinfo/info.xml
Labels: enhancement, 3. to review

#1621 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
