Repository nextcloud/collectives, pull requests merged in 2024-03, with the labels that each got.

#1061 chore: update workflows from templates
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review, dependencies, automated

#1143 chore(ci): Run all summary jobs on `ubuntu-latest-low`
  .github/workflows/app-upgrade-mysql.yml
  .github/workflows/app-upgrade-postgres.yml
  .github/workflows/behat-sqlite-encryption.yml
  .github/workflows/behat-sqlite.yml
  .github/workflows/cypress.yml
  .github/workflows/occ-cli-mysql.yml
Labels: 3. to review

#1065 Set default language for TNTSearch
  lib/Search/FileSearch/FileSearcher.php
  lib/Service/SearchService.php
Labels: enhancement, 4. to release, feedback-requested

#1148 chore: update workflows from templates
  .github/workflows/cypress.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-matrix.yml
Labels: 3. to review, dependencies, automated

#1158 fix(PageList): Fix sort menu button
  src/components/PageList.vue
Labels: 3. to review

#1169 fix(ReferenceProvider): Check `pathinfo` return value before using it
  lib/Reference/SearchablePageReferenceProvider.php
Labels: bug: regression, 3. to review

#1150 Fix anchcors scrolling
  src/Collectives.vue
  src/mixins/editorMixin.js
Labels: bug, 3. to review, feedback-requested

#1179 chore(release): Prepare 2.10.1 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
