Repository nextcloud/collectives, pull requests merged in 2025-09, with the labels that each got.

#1957 Replace MDI icon variant with Material Symbol one
  src/components/Collective/CollectiveActions.vue
  src/components/CollectivePrint.vue
  src/components/Member/Member.vue
  src/components/Nav/CollectivesTrash.vue
  src/components/Nav/TemplateListItem.vue
  src/components/Page/PageActionMenu.vue
  src/components/PageList/PageTrash.vue
  src/components/PageSidebar/SidebarTabAttachments.vue
  src/components/PageSidebar/Version.vue
Labels: design, 3. to review

#1964 Migrate icon from filled to outlined variant
  src/components/Page/TagsModal.vue
Labels: design, 3. to review

#1983 fix(pageList): Current page loading only when moving itself
  src/mixins/pageMixin.js
Labels: papercut, 3. to review

#1996 fix(TagsModal): Don't show a toast when not tags got deleted
  src/components/Page/TagsModal.vue
Labels: bug, papercut, 3. to review

#1998 fix(PageList): fix color of favorite star on Nextcloud 32
  src/components/PageList/Item.vue
Labels: bug, design, papercut, 3. to review, regression
