Repository nextcloud/collectives, pull requests merged in 2025-07, with the labels that each got.

#1845 chore: Remove unused linkHandler mixin
  src/mixins/editorMixin.js
  src/mixins/linkHandlerMixin.js
Labels: 3. to review, technical debt

#1846 fix(GenerateSlugs): Catch error when circle is missing
  lib/Command/GenerateSlugs.php
  lib/Migration/GenerateSlugs.php
Labels: bug, 3. to review

#1861 fix(api): Add getRevision function required by NC 32
  lib/Versions/VersionsBackend.php
Labels: backend, 3. to review

#1863 fix(session): Only initialize a collective session as logged in user
  src/components/Collective.vue
Labels: bug, 3. to review

#1864 chore(cleanup): Remove debugYjs function
  src/mixins/editorMixin.js
Labels: 3. to review, technical debt

#1901 test(cy): Only test link handling against `https` URLs
  .github/workflows/cypress-e2e.yml
  cypress/e2e/pages-links.spec.js
  lib/Service/PageService.php
Labels: tests, 3. to review, regression

#1906 chor(release): Prepare 3.0.3 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review, release

#1909 fix(GenerateSlugs): Stop migration if slugs already got generated
  lib/Migration/GenerateSlugs.php
Labels: bug, 3. to review, regression
