Repository nextcloud/collectives, pull requests merged in 2025-01, with the labels that each got.

#1623 tests(integration): Fix login by setting origin header
  tests/Integration/features/bootstrap/FeatureContext.php
Labels: bug, 3. to review

#1630 fix: hint table for columns for sharded queries
  lib/Mount/CollectiveFolderManager.php
Labels: bug, 3. to review

#1635 chore: Bump max-version to 31
  appinfo/info.xml
Labels: 3. to review, release

#1647 Prepare 2.16.0 release
  CHANGELOG.md
  appinfo/info.xml
Labels: 3. to review
